In [2]:
import pandas as pd
import scipy.io
data = scipy.io.loadmat('water_dataset.mat')

In [19]:
[i[0] for i in data['features'][0]]

['Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Maximum)',
 'pH, water, unfiltered, field, standard units (Maximum)',
 'pH, water, unfiltered, field, standard units (Minimum)',
 'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Minimum)',
 'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Mean)',
 'Dissolved oxygen, water, unfiltered, milligrams per liter (Maximum)',
 'Dissolved oxygen, water, unfiltered, milligrams per liter (Mean)',
 'Dissolved oxygen, water, unfiltered, milligrams per liter (Minimum)',
 'Temperature, water, degrees Celsius (Mean)',
 'Temperature, water, degrees Celsius (Minimum)',
 'Temperature, water, degrees Celsius (Maximum)']

In [3]:
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'X_tr', 'X_te', 'Y_tr', 'Y_te', 'location_group', 'features', 'location_ids'])

In [6]:
data['location_ids']

array([[  2198840],
       [  2198920],
       [  2198950],
       [  2203603],
       [  2203655],
       [  2203700],
       [  2203831],
       [  2203863],
       [  2203873],
       [  2203900],
       [  2203950],
       [  2203960],
       [  2204037],
       [  2207135],
       [  2207160],
       [  2208450],
       [  2208493],
       [  2336120],
       [  2336152],
       [  2336240],
       [  2336300],
       [  2336313],
       [  2336340],
       [  2336360],
       [  2336410],
       [  2336526],
       [  2336728],
       [  2337170],
       [  2344630],
       [  2344673],
       [ 21989715],
       [ 21989773],
       [ 21989792],
       [ 21989793],
       [ 22035975],
       [ 23362095],
       [219897945]], dtype=int32)

In [4]:
data['features']

array([[array(['Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Maximum)'],
              dtype='<U100')                                                                                           ,
        array(['pH, water, unfiltered, field, standard units (Maximum)'],
              dtype='<U54')                                              ,
        array(['pH, water, unfiltered, field, standard units (Minimum)'],
              dtype='<U54')                                              ,
        array(['Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Minimum)'],
              dtype='<U100')                                                                                           ,
        array(['Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Mean)'],
              dtype='<U97')                                                                                         ,
        array(['Dissolved oxygen, water, unfiltered, milligrams per liter (Maximum)'],
              dtype='<U67')                                                           ,
        array(['Dissolved oxygen, water, unfiltered, milligrams per liter (Mean)'],
              dtype='<U64')                                                        ,
        array(['Dissolved oxygen, water, unfiltered, milligrams per liter (Minimum)'],
              dtype='<U67')                                                           ,
        array(['Temperature, water, degrees Celsius (Mean)'], dtype='<U42'),
        array(['Temperature, water, degrees Celsius (Minimum)'], dtype='<U45'),
        array(['Temperature, water, degrees Celsius (Maximum)'], dtype='<U45')]],
      dtype=object)

In [7]:
import numpy as np
features = data['features'][0]
data_dict = {}
values = np.transpose(data['X_tr'][0][0])
for i,v in enumerate(features):
    data_dict[v[0]] = values[i]
    
df = pd.DataFrame(data_dict)

for x in range(1,len(data['X_tr'][0])):
    values = np.transpose(data['X_tr'][0][x])
    for i,v in enumerate(features):
        data_dict[v[0]] = values[i]
    temp_df = pd.DataFrame(data_dict)
    df = pd.concat([df,temp_df])
    
    
df.head()

,"Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Maximum)","pH, water, unfiltered, field, standard units (Maximum)","pH, water, unfiltered, field, standard units (Minimum)","Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Minimum)","Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Mean)","Dissolved oxygen, water, unfiltered, milligrams per liter (Maximum)","Dissolved oxygen, water, unfiltered, milligrams per liter (Mean)","Dissolved oxygen, water, unfiltered, milligrams per liter (Minimum)","Temperature, water, degrees Celsius (Mean)","Temperature, water, degrees Celsius (Minimum)","Temperature, water, degrees Celsius (Maximum)"
0,0.001131,0.884615,0.001120,0.001113,0.677632,0.841463,0.765152,0.787402,0.293750,0.298077,0.276163
1,0.001170,0.871795,0.001159,0.001152,0.703947,0.829268,0.772727,0.795276,0.293750,0.301282,0.276163
2,0.001326,0.884615,0.001198,0.001250,0.677632,0.853659,0.750000,0.755906,0.300000,0.298077,0.287791
3,0.014094,0.858974,0.001238,0.003926,0.697368,0.829268,0.772727,0.771654,0.296875,0.294872,0.279070
4,0.088109,0.858974,0.010766,0.029297,0.684211,0.853659,0.765152,0.755906,0.296875,0.291667,0.281977

In [8]:
df.to_csv('water_x_train.csv',index = False)

In [10]:
features = data['features'][0]
data_dict = {}
values = np.transpose(data['X_te'][0][0])
for i,v in enumerate(features):
    data_dict[v[0]] = values[i]
    
df2 = pd.DataFrame(data_dict)

for x in range(1,len(data['X_te'][0])):
    values = np.transpose(data['X_te'][0][x])
    for i,v in enumerate(features):
        data_dict[v[0]] = values[i]
    temp_df2 = pd.DataFrame(data_dict)
    df2 = pd.concat([df2,temp_df2])
    
    
df2.head()

,"Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Maximum)","pH, water, unfiltered, field, standard units (Maximum)","pH, water, unfiltered, field, standard units (Minimum)","Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Minimum)","Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius (Mean)","Dissolved oxygen, water, unfiltered, milligrams per liter (Maximum)","Dissolved oxygen, water, unfiltered, milligrams per liter (Mean)","Dissolved oxygen, water, unfiltered, milligrams per liter (Minimum)","Temperature, water, degrees Celsius (Mean)","Temperature, water, degrees Celsius (Minimum)","Temperature, water, degrees Celsius (Maximum)"
0,0.002300,0.910256,0.001984,0.002051,0.578947,0.865854,0.651515,0.661417,0.571875,0.573718,0.543605
1,0.243665,0.923077,0.002534,0.110547,0.572368,0.902439,0.575758,0.503937,0.553125,0.541667,0.537791
2,0.208577,0.884615,0.007957,0.095508,0.565789,0.890244,0.583333,0.535433,0.556250,0.544872,0.552326
3,0.391813,0.935897,0.061100,0.228516,0.519737,0.926829,0.530303,0.519685,0.537500,0.528846,0.526163
4,0.497076,0.961538,0.243615,0.353516,0.486842,0.926829,0.530303,0.519685,0.531250,0.528846,0.514535

In [12]:
len(df2) / 37

282.0

In [13]:
df2.to_csv('water_x_test.csv',index = False)

In [27]:
data['Y_te'][1]

In [40]:
data_dict = {'water quality':data['Y_te'][0]}
df3 = pd.DataFrame(data_dict)
for x in range(1,len(data['Y_te'])):
    data_dict = {'water quality':data['Y_te'][x]}
    temp_df3 = pd.DataFrame(data_dict)
    df3 = pd.concat([df3,temp_df3])    
df3.head(5)

   water quality
0       0.666667
1       0.666667
2       0.657407
3       0.657407
4       0.657407

In [39]:
len(df3)

10434

In [41]:
df3.to_csv('water_y_test.csv',index = False)

In [44]:
#data['Y_tr'][0]

In [42]:
data_dict = {'water quality':data['Y_tr'][0]}
df4 = pd.DataFrame(data_dict)
for x in range(1,len(data['Y_tr'])):
    data_dict = {'water quality':data['Y_tr'][x]}
    temp_df4 = pd.DataFrame(data_dict)
    df4 = pd.concat([df4,temp_df4])    
df4.head(5)

   water quality
0       0.648148
1       0.648148
2       0.648148
3       0.648148
4       0.648148

In [45]:
df4.to_csv('water_y_train.csv',index = False)